INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (23, 378, 'Polska', 30);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (24, 378, 'XVIII', 31);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (25, 378, 'Stal', 32);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (26, 379, 'Polska', 30);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (27, 379, 'XX', 31);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (28, 379, 'Stal', 32);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (29, 379, '86,5cm', 33);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (30, 380, 'Polska', 30);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (31, 380, 'XX', 31);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (32, 380, 'Stal', 32);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (33, 380, '90cm', 33);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (34, 381, '1933', 34);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (35, 381, 'Niemcy', 35);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (36, 381, 'Dobry', 36);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (37, 382, '1922', 34);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (38, 382, 'Niemcy', 35);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (39, 382, 'Dobry', 36);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (40, 383, '1942', 34);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (41, 383, 'Rosja', 35);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (42, 383, 'Zły', 36);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (43, 384, 'Irak', 37);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (44, 384, 'Budynek', 38);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (45, 384, 'Dobry', 39);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (46, 385, 'Polska', 37);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (47, 385, 'Postać historyczna', 38);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (48, 385, 'Bardzo dobry', 39);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (49, 386, 'Polska', 37);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (50, 386, 'Postać historyczna', 38);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (51, 386, 'Dobry', 39);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (52, 378, '69 cm', 33);
INSERT INTO m1036_antykwariat.my_collection_attribute (id, my_collection_id, value, attribute_id) VALUES (56, 378, 'fdsf', 43);